import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const FILE_MAP = {
  ARCHITECTURE: 'architecture.md',
  API_ROUTES: 'api-routes.md',
  DATABASE_SCHEMA: 'database-schema.md',
  GETTING_STARTED: 'getting-started.md',
};

export function writeDocs(sections, outputDir) {
  mkdirSync(outputDir, { recursive: true });

  const written = [];

  for (const [section, content] of Object.entries(sections)) {
    const filename = FILE_MAP[section] || `${section.toLowerCase()}.md`;
    const filePath = join(outputDir, filename);
    writeFileSync(filePath, content);
    written.push(filename);
  }

  // Generate an index README
  let index = '# Project Documentation\n\n';
  index += 'Generated by [docgen](https://github.com/parthav/docgen)\n\n';
  index += '## Contents\n\n';

  if (sections.ARCHITECTURE) index += '- [Architecture Overview](./architecture.md)\n';
  if (sections.API_ROUTES) index += '- [API Routes](./api-routes.md)\n';
  if (sections.DATABASE_SCHEMA) index += '- [Database Schema](./database-schema.md)\n';
  if (sections.GETTING_STARTED) index += '- [Getting Started](./getting-started.md)\n';
  index += '- [Dependency Graph](./dependency-graph.md)\n';

  writeFileSync(join(outputDir, 'README.md'), index);
  written.push('README.md');

  return written;
}
